// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATWUczkAMKlLZS2_gpsN-hlJ7AiCFz_oM',
    appId: '1:891091707326:web:f3afd8343fb7d691d105ef',
    messagingSenderId: '891091707326',
    projectId: 'mo-kam',
    authDomain: 'mo-kam.firebaseapp.com',
    storageBucket: 'mo-kam.firebasestorage.app',
    measurementId: 'G-5RSGB39J5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtr_z4K7eroAkmUVXuDlTh6su5wwokb7E',
    appId: '1:891091707326:android:707f429a5eafa16fd105ef',
    messagingSenderId: '891091707326',
    projectId: 'mo-kam',
    storageBucket: 'mo-kam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97eZBbaqAXhymF41pG6eQmxZgMwIbR4Q',
    appId: '1:891091707326:ios:21c3ff1f33cab08cd105ef',
    messagingSenderId: '891091707326',
    projectId: 'mo-kam',
    storageBucket: 'mo-kam.firebasestorage.app',
    iosBundleId: 'com.example.assignmentMokam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA97eZBbaqAXhymF41pG6eQmxZgMwIbR4Q',
    appId: '1:891091707326:ios:21c3ff1f33cab08cd105ef',
    messagingSenderId: '891091707326',
    projectId: 'mo-kam',
    storageBucket: 'mo-kam.firebasestorage.app',
    iosBundleId: 'com.example.assignmentMokam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATWUczkAMKlLZS2_gpsN-hlJ7AiCFz_oM',
    appId: '1:891091707326:web:1c796131e5063eecd105ef',
    messagingSenderId: '891091707326',
    projectId: 'mo-kam',
    authDomain: 'mo-kam.firebaseapp.com',
    storageBucket: 'mo-kam.firebasestorage.app',
    measurementId: 'G-0WTB8KEGK9',
  );
}
